# coding: utf-8

"""
    Stadia Maps Geospatial APIs

    The Stadia Maps Geospatial APIs provide you with the data you need to build awesome applications.

    The version of the OpenAPI document: 6.6.2
    Contact: support@stadiamaps.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stadiamaps.models.bulk_search_request_inner import BulkSearchRequestInner

class TestBulkSearchRequestInner(unittest.TestCase):
    """BulkSearchRequestInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkSearchRequestInner:
        """Test BulkSearchRequestInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkSearchRequestInner`
        """
        model = BulkSearchRequestInner()
        if include_optional:
            return BulkSearchRequestInner(
                endpoint = '/v1/search/structured',
                query = stadiamaps.models.search_structured_query.searchStructuredQuery(
                    address = '11 Wall Street', 
                    neighbourhood = 'Financial District', 
                    borough = 'Manhattan', 
                    locality = 'New York', 
                    county = 'New York County', 
                    region = 'New York', 
                    postal_code = '10005', 
                    country = 'USA', 
                    focus/point/lat = -90, 
                    focus/point/lon = -180, 
                    boundary/rect/min_lat = -90, 
                    boundary/rect/max_lat = -90, 
                    boundary/rect/min_lon = -180, 
                    boundary/rect/max_lon = -180, 
                    boundary/circle/lat = -90, 
                    boundary/circle/lon = -180, 
                    boundary/circle/radius = 1.337, 
                    boundary/country = [
                        ''
                        ], 
                    boundary/gid = '', 
                    layers = [
                        'venue'
                        ], 
                    sources = [
                        'openstreetmap'
                        ], 
                    size = 56, 
                    lang = '', )
            )
        else:
            return BulkSearchRequestInner(
        )
        """

    def testBulkSearchRequestInner(self):
        """Test BulkSearchRequestInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
