# coding: utf-8

"""
    Stadia Maps Geospatial APIs

    The Stadia Maps Geospatial APIs provide you with the data you need to build awesome applications.

    The version of the OpenAPI document: 11.0.0
    Contact: support@stadiamaps.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stadiamaps.models.reverse_query import ReverseQuery

class TestReverseQuery(unittest.TestCase):
    """ReverseQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReverseQuery:
        """Test ReverseQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReverseQuery`
        """
        model = ReverseQuery()
        if include_optional:
            return ReverseQuery(
                point_lat = 48.848268,
                point_lon = 2.294471,
                boundary_circle_radius = 1.337,
                boundary_country = [
                    ''
                    ],
                boundary_gid = '',
                layers = [
                    'venue'
                    ],
                sources = [
                    'openstreetmap'
                    ],
                size = 56,
                lang = ''
            )
        else:
            return ReverseQuery(
        )
        """

    def testReverseQuery(self):
        """Test ReverseQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
