# coding: utf-8

"""
    Stadia Maps Geospatial APIs

    The Stadia Maps Geospatial APIs provide you with the data you need to build awesome applications.

    The version of the OpenAPI document: 7.0.0
    Contact: support@stadiamaps.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stadiamaps.models.osrm_guidance_modifier import OsrmGuidanceModifier

class TestOsrmGuidanceModifier(unittest.TestCase):
    """OsrmGuidanceModifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOsrmGuidanceModifier(self):
        """Test OsrmGuidanceModifier"""
        # inst = OsrmGuidanceModifier()

if __name__ == '__main__':
    unittest.main()
