# coding: utf-8

"""
    Stadia Maps Geospatial APIs

    The Stadia Maps Geospatial APIs provide you with the data you need to build awesome applications.  # noqa: E501

    The version of the OpenAPI document: 5.0.1
    Contact: support@stadiamaps.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import stadiamaps
from stadiamaps.models.map_match_request_all_of import MapMatchRequestAllOf  # noqa: E501
from stadiamaps.rest import ApiException

class TestMapMatchRequestAllOf(unittest.TestCase):
    """MapMatchRequestAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MapMatchRequestAllOf
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MapMatchRequestAllOf`
        """
        model = stadiamaps.models.map_match_request_all_of.MapMatchRequestAllOf()  # noqa: E501
        if include_optional :
            return MapMatchRequestAllOf(
                begin_time = 56, 
                durations = 56, 
                use_timestamps = True, 
                trace_options = stadiamaps.models.map_match_trace_options.mapMatchTraceOptions(
                    search_radius = 56, 
                    gps_accuracy = 1.337, 
                    breakage_distance = 1.337, 
                    interpolation_distance = 1.337, 
                    turn_penalty_factor = 56, ), 
                linear_references = True
            )
        else :
            return MapMatchRequestAllOf(
        )
        """

    def testMapMatchRequestAllOf(self):
        """Test MapMatchRequestAllOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
