# coding: utf-8

"""
    Stadia Maps Geospatial APIs

    The Stadia Maps Geospatial APIs provide you with the data you need to build awesome applications.

    The version of the OpenAPI document: 7.0.0
    Contact: support@stadiamaps.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stadiamaps.models.extended_directions_options import ExtendedDirectionsOptions

class TestExtendedDirectionsOptions(unittest.TestCase):
    """ExtendedDirectionsOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExtendedDirectionsOptions:
        """Test ExtendedDirectionsOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExtendedDirectionsOptions`
        """
        model = ExtendedDirectionsOptions()
        if include_optional:
            return ExtendedDirectionsOptions(
                format = 'json',
                banner_instructions = True,
                voice_instructions = True,
                filters = stadiamaps.models.annotation_filters.annotationFilters(
                    action = 'include', 
                    attributes = [
                        'shape_attributes.speed'
                        ], )
            )
        else:
            return ExtendedDirectionsOptions(
        )
        """

    def testExtendedDirectionsOptions(self):
        """Test ExtendedDirectionsOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
