# coding: utf-8

"""
    Stadia Maps Geospatial APIs

    The Stadia Maps Geospatial APIs provide you with the data you need to build awesome applications.

    The version of the OpenAPI document: 6.6.0
    Contact: support@stadiamaps.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stadiamaps.models.search_bulk_query import SearchBulkQuery

class TestSearchBulkQuery(unittest.TestCase):
    """SearchBulkQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchBulkQuery:
        """Test SearchBulkQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchBulkQuery`
        """
        model = SearchBulkQuery()
        if include_optional:
            return SearchBulkQuery(
                endpoint = '/v1/search',
                query = stadiamaps.models.search_query.searchQuery(
                    text = '1600 Pennsylvania Ave NW', 
                    focus/point/lat = -90, 
                    focus/point/lon = -180, 
                    boundary/rect/min_lat = -90, 
                    boundary/rect/max_lat = -90, 
                    boundary/rect/min_lon = -180, 
                    boundary/rect/max_lon = -180, 
                    boundary/circle/lat = -90, 
                    boundary/circle/lon = -180, 
                    boundary/circle/radius = 1.337, 
                    boundary/country = [
                        ''
                        ], 
                    boundary/gid = '', 
                    layers = [
                        'venue'
                        ], 
                    sources = [
                        'openstreetmap'
                        ], 
                    size = 56, 
                    lang = '', )
            )
        else:
            return SearchBulkQuery(
        )
        """

    def testSearchBulkQuery(self):
        """Test SearchBulkQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
