# coding: utf-8

"""
    Stadia Maps Geospatial APIs

    The Stadia Maps Geospatial APIs provide you with the data you need to build awesome applications.  # noqa: E501

    The version of the OpenAPI document: 5.0.1
    Contact: support@stadiamaps.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import stadiamaps
from stadiamaps.models.matrix_response import MatrixResponse  # noqa: E501
from stadiamaps.rest import ApiException

class TestMatrixResponse(unittest.TestCase):
    """MatrixResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MatrixResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MatrixResponse`
        """
        model = stadiamaps.models.matrix_response.MatrixResponse()  # noqa: E501
        if include_optional :
            return MatrixResponse(
                id = 'kesklinn', 
                sources = [
                    [
                        stadiamaps.models.coordinate.coordinate(
                            lat = 59.436884, 
                            lon = 24.742595, )
                        ]
                    ], 
                targets = [
                    [
                        stadiamaps.models.coordinate.coordinate(
                            lat = 59.436884, 
                            lon = 24.742595, )
                        ]
                    ], 
                sources_to_targets = [
                    [
                        stadiamaps.models.matrix_distance.matrixDistance(
                            distance = 1.337, 
                            time = 56, 
                            from_index = 56, 
                            to_index = 56, )
                        ]
                    ], 
                warnings = [
                    stadiamaps.models.warning.warning(
                        text = '', 
                        code = 56, )
                    ], 
                units = 'kilometers'
            )
        else :
            return MatrixResponse(
                sources = [
                    [
                        stadiamaps.models.coordinate.coordinate(
                            lat = 59.436884, 
                            lon = 24.742595, )
                        ]
                    ],
                targets = [
                    [
                        stadiamaps.models.coordinate.coordinate(
                            lat = 59.436884, 
                            lon = 24.742595, )
                        ]
                    ],
                sources_to_targets = [
                    [
                        stadiamaps.models.matrix_distance.matrixDistance(
                            distance = 1.337, 
                            time = 56, 
                            from_index = 56, 
                            to_index = 56, )
                        ]
                    ],
                units = 'kilometers',
        )
        """

    def testMatrixResponse(self):
        """Test MatrixResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
