# coding: utf-8

"""
    Stadia Maps Geospatial APIs

    The Stadia Maps Geospatial APIs provide you with the data you need to build awesome applications.

    The version of the OpenAPI document: 9.0.0
    Contact: support@stadiamaps.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from stadiamaps.models.geonames_addendum import GeonamesAddendum

class TestGeonamesAddendum(unittest.TestCase):
    """GeonamesAddendum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeonamesAddendum:
        """Test GeonamesAddendum
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeonamesAddendum`
        """
        model = GeonamesAddendum()
        if include_optional:
            return GeonamesAddendum(
                feature_code = ''
            )
        else:
            return GeonamesAddendum(
                feature_code = '',
        )
        """

    def testGeonamesAddendum(self):
        """Test GeonamesAddendum"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
