# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import stadiamaps
from stadiamaps.paths.nearest_roads_v1 import post  # noqa: E501
from stadiamaps import configuration, schemas, api_client

from .. import ApiTestMixin


class TestNearestRoadsV1(ApiTestMixin, unittest.TestCase):
    """
    NearestRoadsV1 unit test stubs
        Find the nearest roads to the set of input locations.  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
