# coding: utf-8

"""
    Stadia Maps Geospatial APIs

    The Stadia Maps Geospatial APIs provide you with the data you need to build awesome applications. All endpoints are versioned individually to allow for granular upgrades. We follow the [Semantic Versioning scheme](https://semver.org/).  # noqa: E501

    The version of the OpenAPI document: 5.0.0
    Contact: support@stadiamaps.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from stadiamaps import schemas  # noqa: F401


class HeightRequest(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            id = schemas.StrSchema
            
            
            class shape(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Coordinate']:
                        return Coordinate
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['Coordinate'], typing.List['Coordinate']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'shape':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Coordinate':
                    return super().__getitem__(i)
            encoded_polyline = schemas.StrSchema
            
            
            class shape_format(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def POLYLINE6(cls):
                    return cls("polyline6")
                
                @schemas.classproperty
                def POLYLINE5(cls):
                    return cls("polyline5")
            range = schemas.BoolSchema
            
            
            class height_precision(
                schemas.IntSchema
            ):
                pass
            __annotations__ = {
                "id": id,
                "shape": shape,
                "encoded_polyline": encoded_polyline,
                "shape_format": shape_format,
                "range": range,
                "height_precision": height_precision,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["shape"]) -> MetaOapg.properties.shape: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["encoded_polyline"]) -> MetaOapg.properties.encoded_polyline: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["shape_format"]) -> MetaOapg.properties.shape_format: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["range"]) -> MetaOapg.properties.range: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["height_precision"]) -> MetaOapg.properties.height_precision: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "shape", "encoded_polyline", "shape_format", "range", "height_precision", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["shape"]) -> typing.Union[MetaOapg.properties.shape, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["encoded_polyline"]) -> typing.Union[MetaOapg.properties.encoded_polyline, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["shape_format"]) -> typing.Union[MetaOapg.properties.shape_format, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["range"]) -> typing.Union[MetaOapg.properties.range, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["height_precision"]) -> typing.Union[MetaOapg.properties.height_precision, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "shape", "encoded_polyline", "shape_format", "range", "height_precision", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        id: typing.Union[MetaOapg.properties.id, str, schemas.Unset] = schemas.unset,
        shape: typing.Union[MetaOapg.properties.shape, list, tuple, schemas.Unset] = schemas.unset,
        encoded_polyline: typing.Union[MetaOapg.properties.encoded_polyline, str, schemas.Unset] = schemas.unset,
        shape_format: typing.Union[MetaOapg.properties.shape_format, str, schemas.Unset] = schemas.unset,
        range: typing.Union[MetaOapg.properties.range, bool, schemas.Unset] = schemas.unset,
        height_precision: typing.Union[MetaOapg.properties.height_precision, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'HeightRequest':
        return super().__new__(
            cls,
            *_args,
            id=id,
            shape=shape,
            encoded_polyline=encoded_polyline,
            shape_format=shape_format,
            range=range,
            height_precision=height_precision,
            _configuration=_configuration,
            **kwargs,
        )

from stadiamaps.model.coordinate import Coordinate
