# coding: utf-8

"""
    Stadia Maps Geospatial APIs

    The Stadia Maps Geospatial APIs provide you with the data you need to build awesome applications. All endpoints are versioned individually to allow for granular upgrades. We follow the [Semantic Versioning scheme](https://semver.org/).  # noqa: E501

    The version of the OpenAPI document: 5.0.0
    Contact: support@stadiamaps.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from stadiamaps import schemas  # noqa: F401


class IsochroneRequest(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "costing",
            "locations",
            "contours",
        }
        
        class properties:
            
            
            class locations(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Coordinate']:
                        return Coordinate
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['Coordinate'], typing.List['Coordinate']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'locations':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Coordinate':
                    return super().__getitem__(i)
        
            @staticmethod
            def costing() -> typing.Type['IsochroneCostingModel']:
                return IsochroneCostingModel
            
            
            class contours(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    max_items = 4
                    min_items = 1
                    
                    @staticmethod
                    def items() -> typing.Type['Contour']:
                        return Contour
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['Contour'], typing.List['Contour']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'contours':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Contour':
                    return super().__getitem__(i)
            id = schemas.StrSchema
        
            @staticmethod
            def costing_options() -> typing.Type['CostingOptions']:
                return CostingOptions
            polygons = schemas.BoolSchema
            
            
            class denoise(
                schemas.Float64Schema
            ):
            
            
                class MetaOapg:
                    format = 'double'
                    inclusive_maximum = 1
                    inclusive_minimum = 0
            generalize = schemas.Float64Schema
            show_locations = schemas.BoolSchema
            __annotations__ = {
                "locations": locations,
                "costing": costing,
                "contours": contours,
                "id": id,
                "costing_options": costing_options,
                "polygons": polygons,
                "denoise": denoise,
                "generalize": generalize,
                "show_locations": show_locations,
            }
    
    costing: 'IsochroneCostingModel'
    locations: MetaOapg.properties.locations
    contours: MetaOapg.properties.contours
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["locations"]) -> MetaOapg.properties.locations: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["costing"]) -> 'IsochroneCostingModel': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["contours"]) -> MetaOapg.properties.contours: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["costing_options"]) -> 'CostingOptions': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["polygons"]) -> MetaOapg.properties.polygons: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["denoise"]) -> MetaOapg.properties.denoise: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["generalize"]) -> MetaOapg.properties.generalize: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["show_locations"]) -> MetaOapg.properties.show_locations: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["locations", "costing", "contours", "id", "costing_options", "polygons", "denoise", "generalize", "show_locations", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["locations"]) -> MetaOapg.properties.locations: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["costing"]) -> 'IsochroneCostingModel': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["contours"]) -> MetaOapg.properties.contours: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["costing_options"]) -> typing.Union['CostingOptions', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["polygons"]) -> typing.Union[MetaOapg.properties.polygons, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["denoise"]) -> typing.Union[MetaOapg.properties.denoise, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["generalize"]) -> typing.Union[MetaOapg.properties.generalize, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["show_locations"]) -> typing.Union[MetaOapg.properties.show_locations, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["locations", "costing", "contours", "id", "costing_options", "polygons", "denoise", "generalize", "show_locations", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        costing: 'IsochroneCostingModel',
        locations: typing.Union[MetaOapg.properties.locations, list, tuple, ],
        contours: typing.Union[MetaOapg.properties.contours, list, tuple, ],
        id: typing.Union[MetaOapg.properties.id, str, schemas.Unset] = schemas.unset,
        costing_options: typing.Union['CostingOptions', schemas.Unset] = schemas.unset,
        polygons: typing.Union[MetaOapg.properties.polygons, bool, schemas.Unset] = schemas.unset,
        denoise: typing.Union[MetaOapg.properties.denoise, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        generalize: typing.Union[MetaOapg.properties.generalize, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        show_locations: typing.Union[MetaOapg.properties.show_locations, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'IsochroneRequest':
        return super().__new__(
            cls,
            *_args,
            costing=costing,
            locations=locations,
            contours=contours,
            id=id,
            costing_options=costing_options,
            polygons=polygons,
            denoise=denoise,
            generalize=generalize,
            show_locations=show_locations,
            _configuration=_configuration,
            **kwargs,
        )

from stadiamaps.model.contour import Contour
from stadiamaps.model.coordinate import Coordinate
from stadiamaps.model.costing_options import CostingOptions
from stadiamaps.model.isochrone_costing_model import IsochroneCostingModel
