# coding: utf-8

"""
    Stadia Maps Geospatial APIs

    The Stadia Maps Geospatial APIs provide you with the data you need to build awesome applications. All endpoints are versioned individually to allow for granular upgrades. We follow the [Semantic Versioning scheme](https://semver.org/).  # noqa: E501

    The version of the OpenAPI document: 5.0.0
    Contact: support@stadiamaps.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from stadiamaps import schemas  # noqa: F401


class MatrixDistance(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "from_index",
            "distance",
            "time",
            "to_index",
        }
        
        class properties:
            distance = schemas.Float64Schema
            time = schemas.IntSchema
            from_index = schemas.IntSchema
            to_index = schemas.IntSchema
            __annotations__ = {
                "distance": distance,
                "time": time,
                "from_index": from_index,
                "to_index": to_index,
            }
    
    from_index: MetaOapg.properties.from_index
    distance: MetaOapg.properties.distance
    time: MetaOapg.properties.time
    to_index: MetaOapg.properties.to_index
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["distance"]) -> MetaOapg.properties.distance: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["time"]) -> MetaOapg.properties.time: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["from_index"]) -> MetaOapg.properties.from_index: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["to_index"]) -> MetaOapg.properties.to_index: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["distance", "time", "from_index", "to_index", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["distance"]) -> MetaOapg.properties.distance: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["time"]) -> MetaOapg.properties.time: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["from_index"]) -> MetaOapg.properties.from_index: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["to_index"]) -> MetaOapg.properties.to_index: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["distance", "time", "from_index", "to_index", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        from_index: typing.Union[MetaOapg.properties.from_index, decimal.Decimal, int, ],
        distance: typing.Union[MetaOapg.properties.distance, decimal.Decimal, int, float, ],
        time: typing.Union[MetaOapg.properties.time, decimal.Decimal, int, ],
        to_index: typing.Union[MetaOapg.properties.to_index, decimal.Decimal, int, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'MatrixDistance':
        return super().__new__(
            cls,
            *_args,
            from_index=from_index,
            distance=distance,
            time=time,
            to_index=to_index,
            _configuration=_configuration,
            **kwargs,
        )
