# coding: utf-8

"""
    Stadia Maps Geospatial APIs

    The Stadia Maps Geospatial APIs provide you with the data you need to build awesome applications. All endpoints are versioned individually to allow for granular upgrades. We follow the [Semantic Versioning scheme](https://semver.org/).  # noqa: E501

    The version of the OpenAPI document: 5.0.0
    Contact: support@stadiamaps.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from stadiamaps import schemas  # noqa: F401


class Restrictions(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            golf_cart = schemas.BoolSchema
            truck = schemas.BoolSchema
            pedestrian = schemas.BoolSchema
            wheelchair = schemas.BoolSchema
            taxi = schemas.BoolSchema
            HOV = schemas.BoolSchema
            emergency = schemas.BoolSchema
            motorcycle = schemas.BoolSchema
            car = schemas.BoolSchema
            moped = schemas.BoolSchema
            bus = schemas.BoolSchema
            bicycle = schemas.BoolSchema
            __annotations__ = {
                "golf_cart": golf_cart,
                "truck": truck,
                "pedestrian": pedestrian,
                "wheelchair": wheelchair,
                "taxi": taxi,
                "HOV": HOV,
                "emergency": emergency,
                "motorcycle": motorcycle,
                "car": car,
                "moped": moped,
                "bus": bus,
                "bicycle": bicycle,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["golf_cart"]) -> MetaOapg.properties.golf_cart: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["truck"]) -> MetaOapg.properties.truck: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["pedestrian"]) -> MetaOapg.properties.pedestrian: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["wheelchair"]) -> MetaOapg.properties.wheelchair: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["taxi"]) -> MetaOapg.properties.taxi: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["HOV"]) -> MetaOapg.properties.HOV: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["emergency"]) -> MetaOapg.properties.emergency: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["motorcycle"]) -> MetaOapg.properties.motorcycle: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["car"]) -> MetaOapg.properties.car: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["moped"]) -> MetaOapg.properties.moped: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bus"]) -> MetaOapg.properties.bus: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["bicycle"]) -> MetaOapg.properties.bicycle: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["golf_cart", "truck", "pedestrian", "wheelchair", "taxi", "HOV", "emergency", "motorcycle", "car", "moped", "bus", "bicycle", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["golf_cart"]) -> typing.Union[MetaOapg.properties.golf_cart, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["truck"]) -> typing.Union[MetaOapg.properties.truck, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["pedestrian"]) -> typing.Union[MetaOapg.properties.pedestrian, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["wheelchair"]) -> typing.Union[MetaOapg.properties.wheelchair, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["taxi"]) -> typing.Union[MetaOapg.properties.taxi, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["HOV"]) -> typing.Union[MetaOapg.properties.HOV, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["emergency"]) -> typing.Union[MetaOapg.properties.emergency, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["motorcycle"]) -> typing.Union[MetaOapg.properties.motorcycle, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["car"]) -> typing.Union[MetaOapg.properties.car, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["moped"]) -> typing.Union[MetaOapg.properties.moped, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bus"]) -> typing.Union[MetaOapg.properties.bus, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["bicycle"]) -> typing.Union[MetaOapg.properties.bicycle, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["golf_cart", "truck", "pedestrian", "wheelchair", "taxi", "HOV", "emergency", "motorcycle", "car", "moped", "bus", "bicycle", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        golf_cart: typing.Union[MetaOapg.properties.golf_cart, bool, schemas.Unset] = schemas.unset,
        truck: typing.Union[MetaOapg.properties.truck, bool, schemas.Unset] = schemas.unset,
        pedestrian: typing.Union[MetaOapg.properties.pedestrian, bool, schemas.Unset] = schemas.unset,
        wheelchair: typing.Union[MetaOapg.properties.wheelchair, bool, schemas.Unset] = schemas.unset,
        taxi: typing.Union[MetaOapg.properties.taxi, bool, schemas.Unset] = schemas.unset,
        HOV: typing.Union[MetaOapg.properties.HOV, bool, schemas.Unset] = schemas.unset,
        emergency: typing.Union[MetaOapg.properties.emergency, bool, schemas.Unset] = schemas.unset,
        motorcycle: typing.Union[MetaOapg.properties.motorcycle, bool, schemas.Unset] = schemas.unset,
        car: typing.Union[MetaOapg.properties.car, bool, schemas.Unset] = schemas.unset,
        moped: typing.Union[MetaOapg.properties.moped, bool, schemas.Unset] = schemas.unset,
        bus: typing.Union[MetaOapg.properties.bus, bool, schemas.Unset] = schemas.unset,
        bicycle: typing.Union[MetaOapg.properties.bicycle, bool, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Restrictions':
        return super().__new__(
            cls,
            *_args,
            golf_cart=golf_cart,
            truck=truck,
            pedestrian=pedestrian,
            wheelchair=wheelchair,
            taxi=taxi,
            HOV=HOV,
            emergency=emergency,
            motorcycle=motorcycle,
            car=car,
            moped=moped,
            bus=bus,
            bicycle=bicycle,
            _configuration=_configuration,
            **kwargs,
        )
