# coding: utf-8

"""
    Stadia Maps Geospatial APIs

    The Stadia Maps Geospatial APIs provide you with the data you need to build awesome applications. All endpoints are versioned individually to allow for granular upgrades. We follow the [Semantic Versioning scheme](https://semver.org/).  # noqa: E501

    The version of the OpenAPI document: 5.0.0
    Contact: support@stadiamaps.com
    Generated by: https://openapi-generator.tech
"""

from stadiamaps.paths.geocoding_v1_autocomplete.get import Autocomplete
from stadiamaps.paths.geocoding_v1_place.get import Place
from stadiamaps.paths.geocoding_v1_reverse.get import Reverse
from stadiamaps.paths.geocoding_v1_search.get import Search
from stadiamaps.paths.geocoding_v1_search_structured.get import SearchStructured


class GeocodingApi(
    Autocomplete,
    Place,
    Reverse,
    Search,
    SearchStructured,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
