# coding: utf-8

"""
    Stadia Maps Geospatial APIs

    The Stadia Maps Geospatial APIs provide you with the data you need to build awesome applications. All endpoints are versioned individually to allow for granular upgrades. We follow the [Semantic Versioning scheme](https://semver.org/).  # noqa: E501

    The version of the OpenAPI document: 5.0.0
    Contact: support@stadiamaps.com
    Generated by: https://openapi-generator.tech
"""

from stadiamaps.paths.isochrone_v1.post import Isochrone
from stadiamaps.paths.map_match_v1.post import MapMatch
from stadiamaps.paths.nearest_roads_v1.post import NearestRoads
from stadiamaps.paths.optimized_route_v1.post import OptimizedRoute
from stadiamaps.paths.route_v1.post import Route
from stadiamaps.paths.matrix_v1.post import TimeDistanceMatrix
from stadiamaps.paths.trace_attributes_v1.post import TraceAttributes


class RoutingApi(
    Isochrone,
    MapMatch,
    NearestRoads,
    OptimizedRoute,
    Route,
    TimeDistanceMatrix,
    TraceAttributes,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
